Mockup Pastie Endpoints
HackerPaste/HackerPaste pull request #25
Opened 2016-10-15 22:22 UTC by carsontmoore

First mock of Pastie endpoints on backend.  Addresses #15, #16, and #20.

2016-10-15 22:38 UTC, gilbert requested changes
Nice job, this is pretty much what the API will end up looking like :)

2016-10-15 22:38 UTC, mindeavor commented on server/apis/pasties-api.js
> +		.catch( Pastie.InvalidFormat, API.prep(404, res) )
404 means "Not found" – 400 more appropriately means "error caused by the client"

2016-10-15 22:38 UTC, mindeavor commented on server/apis/pasties-api.js
> +	Pastie.findWhere( req.query )
I think `Pastie.feedForUser( req.user.uid )` would be a more accurate mockup :)

2016-10-15 22:38 UTC, mindeavor commented on server/apis/pasties-api.js
> +    .catch( API.catchUnexpectedErrors )
Indenting

2016-10-15 22:38 UTC, mindeavor commented on server/apis/pasties-api.js
> +    .catch( API.catchUnexpectedErrors )
Also make sure you use spaces (2) instead of tabs

2016-10-15 23:39 UTC, shamsup commented on server/apis/pasties-api.js
> +	Pastie.findWhere( req.query )
That name makes more sense. 
Additionally, the `req.query` portion is for the potential of adding search further into the project, so would it be wise to still include that part? ie `Pastie.feedForUser(req.user.uid, req.query)`

2016-10-16 00:03 UTC, mindeavor commented on server/apis/pasties-api.js
> +	Pastie.findWhere( req.query )
Yes, that is perfectly ok :)

2016-10-16 17:56 UTC, shamsup approved these changes
Everything looks good

2016-10-16 18:48 UTC, gilbert approved these changes

2016-10-16 19:40 UTC, merged