Feat22 makerpass auth
HackerPaste/HackerPaste pull request #26
Opened 2016-10-16 23:28 UTC by shamsup

#22

2016-10-16 23:55 UTC, gilbert requested changes
Good job! Be sure to fix your commit history before merging, unless you're planning to squash-merge.

2016-10-16 23:55 UTC, mindeavor commented on server/index.js
> +routes.use(MP.authWithSession({ required: false }));
I recommend moving this middleware to the `routes.use('/api')` pipeline to avoid making the extra request for the catch-all route

2016-10-17 00:06 UTC, shamsup commented
Be sure to edit the commit comments after the squash

2016-10-17 03:20 UTC, gilbert approved these changes

2016-10-17 15:10 UTC, merged