Adds mockup for landing page
HackerPaste/HackerPaste pull request #45
Opened 2016-10-19 19:56 UTC by ArtyEmsee

2016-10-19 20:22 UTC, shamsup requested changes
Remove the .DS_Store files. It's probably worth adding a line in .gitignore.

Move the source files and any unused images out of `/client/public` since our users shouldn't be able to see those.

2016-10-19 20:22 UTC, shamsup commented on client/public/assets/style.css
> +}
Can we just create 1 `.box` that accomplishes both of these? I don't think they need fixed heights. I think growing automatically is fine.

2016-10-19 20:22 UTC, shamsup commented on client/public/index.html
> +      <input class="logo" type="image" src="assets/logo.png" href=""/> <!-- Create home link functionality -->
This should be an `a` tag with an image inside of it or a background image

2016-10-19 20:22 UTC, shamsup commented on client/public/index.html
> +          <a class="user-filter-btn">Filter ⌄</a>
Swap this dropdown for tabs across the top `Feed | Public`

2016-10-19 20:22 UTC, shamsup commented on client/public/index.html
> +        <div class="box-lower-right">
Change these to just be `.box` to match the requested change in the CSS.

2016-10-19 20:22 UTC, shamsup commented on client/public/index.html
> +            <h>My Pasties</h>
Should be a h1-h6 element. Probably an h2 or h3.

2016-10-19 20:22 UTC, shamsup commented on client/public/index.html
> +                <p><a>This is where the beginning of the snippet would go. Blahhhhh...</a></p>
In this section of the sidebar, we can probably drop the preview text and just show the title. The user should know what each of their snippets are. It could be something we can change pretty easily in the future

2016-10-19 20:22 UTC, shamsup commented on client/public/style reference/reactorcore/base/_variables.less
> +//Basic stylings
Less files shouldn't be in `/client/public`. They should be moved to `/client/less` or something similar. Source files should not be visible to a user

2016-10-19 20:22 UTC, shamsup commented on client/public/assets/style.css
> +
We probably want to convert this to less and use it in conjunction with the other reactorcore styles.

2016-10-19 21:03 UTC, ArtyEmsee commented on client/public/assets/style.css
> +}
With automatic growth, that could potentially push the users own posts way down the page, if the person using it were staff.. Thoughts?

2016-10-19 21:16 UTC, shamsup commented on client/public/assets/style.css
> +}
I don't think that's anything to be concerned about. We could also only show like 4-5 groups initially, and have a little link that clicks to show the rest, but I think a staff member would probably be more interested in the groups they're a part of rather than the pasties they've created

2016-10-20 05:07 UTC, shamsup commented on client/public/index.html
> +        <a class="create-pastie-btn">CREATE</a>
anchor elements should always have an `href` attribute

2016-10-21 20:18 UTC, shamsup approved these changes
This is a really good starting point now, especially with the less set up

2016-10-21 20:19 UTC, merged