Pastie.ownedByUser & Permission Denied
HackerPaste/HackerPaste pull request #56
Opened 2016-10-21 02:45 UTC by arvinwallace

Added a PermissionDenied handler and Pastie.ownedByUser method

2016-10-21 15:31 UTC, gilbert submitted a review, later dismissed

2016-10-21 15:31 UTC, mindeavor commented on server/models/pastie.js
> +      if (rows.length === 0) { throw new Pastie.NotFound(user_uid) }
For this method it's ok if no pasties are returned. That would just mean the user has not created any pasties; no need to throw an error.

2016-10-21 15:31 UTC, mindeavor commented on server/models/pastie.js
> +  if(user_uid === undefined){throw new Pastie.PermissionDenied(user_uid)}
Instead of naming this error `PermissionDenied`, name it `InvalidArgument`, which will indicate that `user_uid` is required.

2016-10-21 17:32 UTC, arvinwallace commented on server/models/pastie.js
> +      if (rows.length === 0) { throw new Pastie.NotFound(user_uid) }
so do I take the "throw" out and replace it with "alert" ? Is there another way to apply the error handler "InvalidArgument" here?

2016-10-21 17:33 UTC, arvinwallace commented on server/models/pastie.js
> +      if (rows.length === 0) { throw new Pastie.NotFound(user_uid) }
I know that "throw" short circuits things, so I'm wondering if I should be using something that doesn't shut things down immediately

2016-10-21 17:45 UTC, arvinwallace commented on server/models/pastie.js
> +      if (rows.length === 0) { throw new Pastie.NotFound(user_uid) }
I guess what I'm saying is should we not throw an error at all here, and just let the second throw error indicate that user doesn't exist?

2016-10-21 20:13 UTC, shamsup commented on server/models/pastie.js
> +      if (rows.length === 0) { throw new Pastie.NotFound(user_uid) }
It should just resolve to the empty array if they don't have any. The errors are only for when things actually go wrong, like trying to `.find` a pastie that doesn't exist. If a user had an empty feed or hasn't created any pasties, it's okay if it's empty.

2016-10-21 20:15 UTC, shamsup commented on server/models/pastie.js
> +  if(user_uid === undefined){throw new Pastie.PermissionDenied(user_uid)}
I don't think we'll ever get to this method without having a user to pass in on the API end, so this error is probably more of a heads up to the person working on the endpoint for it, and it should never get back to the end user

2016-10-21 20:49 UTC, arvinwallace commented on server/models/pastie.js
> +      if (rows.length === 0) { throw new Pastie.NotFound(user_uid) }
Confused.. So should I take it out? I wrote it because I thought the test was looking for an undefined user, and then specified the error handler named "Permission Denied"

2016-10-21 21:03 UTC, shamsup commented on server/models/pastie.js
> +      if (rows.length === 0) { throw new Pastie.NotFound(user_uid) }
This change is separate from the one above for the undefined user

2016-10-21 23:36 UTC, arvinwallace commented on server/models/pastie.js
> +      if (rows.length === 0) { throw new Pastie.NotFound(user_uid) }
Ok..oops,  I got mixed up there.. I've made a new commit, hopefully it reflects what you guys were requesting..

2016-10-22 04:30 UTC, shamsup requested changes

2016-10-22 04:30 UTC, shamsup commented on server/models/pastie.js
>    constructor(user_uid) {
Let's have it accept an argument name as `argName`, then in the reason we can say `argName + ' is required'`.
We should be able to reuse this error for multiple cases

2016-10-22 04:30 UTC, shamsup commented on server/models/pastie.js
> +      console.log(rows);
Let's not include this console.log in the pull. It's helpful to include them when you're working on the feature, but after it's complete we shouldn't have any sneaking into master.

2016-10-22 15:21 UTC, arvinwallace commented
This model passes all tests now, handles undefined error And the Tests reflect the new name for the Error model suggested by Gilbert

2016-10-22 18:23 UTC, shamsup approved these changes

2016-10-23 21:36 UTC, merged