Feat 57 Adds React Components for HomeFeed and UserGroups
HackerPaste/HackerPaste pull request #64
Opened 2016-10-22 20:30 UTC by ArtyEmsee

2016-10-22 21:28 UTC, shamsup requested changes

2016-10-22 21:28 UTC, shamsup commented on client/components/Router.js
> +var Link = require('react-router').Link
We aren't using react-router. See the example in [the frontend architecture](https://notehub.org/1t1fq#index-js)

2016-10-22 21:28 UTC, shamsup commented on client/components/NewPastie.js
> +      <nav>
Nav will be persistent across all the routes, and it will only be included from the main `App` component. This NewPastie component should just handle the rendering of the container where the textarea and stuff goes for creating a new pastie

2016-10-22 21:28 UTC, shamsup commented on client/public/index.html
>    <link rel='shortcut icon' href='assets/favicon.ico' type='image/x-icon'/ >
Let's not include changes to the `index.html` file unless it's taking it back down to the barebones `<div id="app"></div>` kind of structure. If you want to make those changes, create a new `mockup.html` file that contains all of the old static html contents for reference.

2016-10-22 21:28 UTC, shamsup commented on client/app.js
> +<<<<<<< HEAD
The current version of this file already contains everything we need.

2016-10-22 21:56 UTC, shamsup commented on client/app.js
>  var React = require('react');
The current version of this file already contains everything we need.

2016-10-23 01:36 UTC, shamsup requested changes
Watch for opportunities to avoid extraneous markup like `div` elements with no classes or styling just for the sake of wrapping components

2016-10-23 01:36 UTC, shamsup commented on client/components/HomeFeed.js
> +const HomeFeed = module.exports = (props) => {
This can go back to just being wrapped in `()` rather than `{}`

2016-10-23 01:36 UTC, shamsup commented on client/components/HomeFeed.js
> +  return <div className="container">
Remove the return statement because of the change above

2016-10-23 01:36 UTC, shamsup commented on client/components/HomeFeed.js
> +        <div className="box">
drop the `<div className="box">` in favor of including it inside of the `MyGroupsBox` component

2016-10-23 01:36 UTC, shamsup commented on client/components/HomeFeed.js
> +        <div className="box">
Same as above

2016-10-23 01:36 UTC, shamsup commented on client/components/MyGroupsBox.js
> +  <div>
Change to `<div className="box">` to reflect the changes from the `HomeFeed` component

2016-10-23 01:36 UTC, shamsup commented on client/components/MyPastiesBox.js
> +  <div>
Change to `<div className="box">` to reflect the changes in the `HomeFeed` component

2016-10-23 01:36 UTC, shamsup commented on client/components/MyProfileBox.js
> +  <div className="box-title">
Wrap this in a `<div className="box">` since there will be more elements to add after the `box-title`

2016-10-23 01:36 UTC, shamsup commented on client/components/UsersGroups.js
> +        <div className="box">
Drop the `<div className="box">` in favor of including it in the `MyProfileBox` component

2016-10-23 01:36 UTC, shamsup commented on client/components/UsersGroups.js
> +        <div className="box">
Same as above

2016-10-23 01:36 UTC, shamsup commented on client/public/index.html
>  </html>
Add another file with the static HTML mockup before deleting it all from the repo so that others have a reference

2016-10-23 01:36 UTC, shamsup commented on client/components/FeedList.js
> +  <div>
add `className="feed"` and remove the wrappers from the parent components

2016-10-23 01:36 UTC, shamsup commented on client/components/HomeFeed.js
> +        <div className="feed">
Remove the `<div className="feed">` in favor of including it inside of the `FeedList` component.

2016-10-23 01:36 UTC, shamsup commented on client/components/UsersGroups.js
> +        <div className="feed">
Remove the `<div className="feed">` in favor of including it in the `FeedList` component

2016-10-23 02:52 UTC, mindeavor commented on client/components/FeedList.js
> +        />
Putting this into a helper component is good. I recommend not separating it into its own file unless it is used in multiple components; putting it at the bottom of this file is perfectly ok.

2016-10-23 18:23 UTC, closed without merging